# Fonts
font_family family="JetBrains Mono"
bold_font postscript_name=JetBrainsMono-Bold
italic_font postscript_name=JetBrainsMono-Italic
bold_italic_font postscript_name=JetBrainsMono-BoldItalic

font_size 14.0
disable_ligatures never

modify_font cell_width 100%
modify_font cell_height 125%
modify_font baseline 0 

modify_font underline_position 2px
modify_font underline_thickness 100%
modify_font strikethrough_position 6px

# Text Cursor
cursor_shape beam

# Scrollback
scrollback_lines 100000000

# Mouse
open_url_with default
detect_urls yes
show_hyperlink_targets no

copy_on_select yes
strip_trailing_spaces smart

## Mouse Actions
### Use cmd+left instead of left to open links
mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map cmd+left click grabbed,ungrabbed mouse_handle_click selection link prompt

# Performance Tuning
# input_delay 3

# Terminal Bell
enable_audio_bell no

# Window layout
enabled_layouts Tall
hide_window_decorations no

# Tab bar
tab_bar_edge bottom
tab_bar_align left
tab_bar_style powerline

# Color scheme
background_opacity 0.75
background_blur 60

## Used together with neovim :hi CursorLine guibg=#212121
transparent_background_colors #212121@0.64

background_image bg.jpg
background_image_layout cscaled
background_image_linear yes
background_tint 0.95

# Advanced
clipboard_control write-primary write-clipboard no-append
shell_integration enabled

# Keyboard shortcuts
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

