# Shader keybindings
alt+0 no-osd change-list glsl-shaders set "~~/shaders/KrigBilateral.glsl:~~/shaders/SSimDownscaler.glsl:~~/shaders/SSimSuperRes.glsl"; show-text "GLSL shaders reset to default"
alt+1 no-osd change-list glsl-shaders set "~~/shaders/KrigBilateral.glsl:~~/shaders/SSimDownscaler.glsl:~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"; show-text "FSRCNNX enabled"
alt+2 no-osd change-list glsl-shaders append  "~~/shaders/adaptive-sharpen.glsl"; show-text "adaptive-sharpen.glsl enabled"
