# terminal
# set -g default-terminal 'tmux-256color'
# set -sa terminal-features ',xterm-kitty:RGB'

# set default shell to zsh
set -g default-command zsh

# faster command sequences
set -s escape-time 0

# increase repeat timeout
set -g repeat-time 500

# pass focus events to terminal applications
set -g focus-events on

# increase scrollback buffer size
set -g history-limit 100000000

# enable vi-mode (ctrl+[)
set -g mode-keys vi 

# enable mouse
set -g mouse on

# clipboard integration
set -g set-clipboard external

# enable passthrough
set -g allow-passthrough on

# slightly longer pane indicators display time
# set -g display-panes-time 800 
# slightly longer status messages display time
# set -g display-time 1000

# pane display
set -g pane-base-index 1
set -g pane-border-status top
set -g pane-border-format ' #{pane_index}:#{pane_current_command} '
set -g pane-border-style fg=colour243
set -g pane-active-border-style fg=colour119

# window display
set -g window-status-separator ' | '
# start windows numbering at 1
set -g base-index 1
# renumber windows when a window is closed
set -g renumber-windows on
# rename window to reflect current program
set -g automatic-rename on
# inactive window
set -g window-status-format '#I:#W-#{?window_zoomed_flag,Z,}'
set -g window-status-style fg=colour243
# active window
set -g window-status-current-format '➤#I:#W*#{?window_zoomed_flag,Z,}'
set -g window-status-current-style fg=colour119 # Highlight the current window.

# status display
set -g status on
set -g status-interval 1
set -g status-justify left # absolute-centre
set -g status-style fg=white,bg=black

set -g status-left-length 1000
set -g status-left-style default
set -g status-left '#{session_name}  '

set -g status-right-length 1000
set -g status-right-style default
set -g status-right "#(pwd)  Uptime: #(uptime | cut -d',' -f1 | sed 's/.*up *//')  Power:#(~/.config/tmux/battery.sh)  %Y-%m-%d %H:%M:%S"

# cursor style
set -g cursor-style bar
set -g prompt-cursor-style bar

# activity
set -g monitor-activity on
set -g visual-activity off
set -g window-status-activity-style fg=yellow,bg=black

# set terminal title
set -g set-titles on
set -g set-titles-string '#(hostname -s): #{pane_current_command}'

# copy mode style
set -g mode-style 'fg=black,bg=#fffacd'

# message style
set -g message-style fg=white

# clear both screen and history (need sleep 0.05 to ensure execution order)
bind -n C-l send-keys C-l \; run 'sleep 0.05' \; clear-history

# reload tmux config file
bind r source ~/.config/tmux/tmux.conf 

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

# buffers
bind b list-buffers     # list paste buffers
bind p paste-buffer -p  # paste from the top paste buffer
bind P choose-buffer    # choose which buffer to paste from

# vi-mode keymap
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection # copy-selection-no-clear / copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel

# mouse copy
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel

unbind-key -T root MouseDown3Pane
unbind-key -T root MouseUp3Pane

unbind-key -T copy-mode-vi MouseDown3Pane
unbind-key -T copy-mode-vi MouseUp3Pane
